/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Multisig {
  export type TransactionStruct = {
    spender: AddressLike;
    amount: BigNumberish;
    approvals: BigNumberish;
    isActive: boolean;
  };

  export type TransactionStructOutput = [
    spender: string,
    amount: bigint,
    approvals: bigint,
    isActive: boolean
  ] & { spender: string; amount: bigint; approvals: bigint; isActive: boolean };
}

export interface MultisigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ApproveTransaction"
      | "CalculateMinApprovals"
      | "CreateTransaction"
      | "GetBalance"
      | "GetTransaction"
      | "admins"
      | "approvals"
      | "isAdmin"
      | "transactionId"
      | "transactions"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransactionCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "ApproveTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "CalculateMinApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CreateTransaction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "GetBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "GetTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "admins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvals",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ApproveTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CalculateMinApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CreateTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GetBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GetTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approvals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
}

export namespace TransactionCreatedEvent {
  export type InputTuple = [
    admin: AddressLike,
    txIndex: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    admin: string,
    txIndex: bigint,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    admin: string;
    txIndex: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Multisig extends BaseContract {
  connect(runner?: ContractRunner | null): Multisig;
  waitForDeployment(): Promise<this>;

  interface: MultisigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ApproveTransaction: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  CalculateMinApprovals: TypedContractMethod<[], [bigint], "view">;

  CreateTransaction: TypedContractMethod<
    [_spender: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  GetBalance: TypedContractMethod<[_of: AddressLike], [bigint], "view">;

  GetTransaction: TypedContractMethod<
    [_id: BigNumberish],
    [Multisig.TransactionStructOutput],
    "view"
  >;

  admins: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approvals: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isAdmin: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transactionId: TypedContractMethod<[], [bigint], "view">;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        spender: string;
        amount: bigint;
        approvals: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ApproveTransaction"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "CalculateMinApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CreateTransaction"
  ): TypedContractMethod<
    [_spender: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "GetBalance"
  ): TypedContractMethod<[_of: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "GetTransaction"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [Multisig.TransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approvals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transactionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        spender: string;
        amount: bigint;
        approvals: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TransactionCreated"
  ): TypedContractEvent<
    TransactionCreatedEvent.InputTuple,
    TransactionCreatedEvent.OutputTuple,
    TransactionCreatedEvent.OutputObject
  >;

  filters: {
    "TransactionCreated(address,uint256,address,uint256)": TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;
    TransactionCreated: TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;
  };
}
