/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MultiSigFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CreateMultiSigWallet"
      | "GetDeployedWallets"
      | "deployedWallets"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CreateMultiSigWalletEvent"): EventFragment;

  encodeFunctionData(
    functionFragment: "CreateMultiSigWallet",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "GetDeployedWallets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployedWallets",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CreateMultiSigWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GetDeployedWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedWallets",
    data: BytesLike
  ): Result;
}

export namespace CreateMultiSigWalletEventEvent {
  export type InputTuple = [
    newWallet: AddressLike,
    from: AddressLike,
    admins: AddressLike[]
  ];
  export type OutputTuple = [newWallet: string, from: string, admins: string[]];
  export interface OutputObject {
    newWallet: string;
    from: string;
    admins: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiSigFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MultiSigFactory;
  waitForDeployment(): Promise<this>;

  interface: MultiSigFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CreateMultiSigWallet: TypedContractMethod<
    [_admins: AddressLike[]],
    [void],
    "payable"
  >;

  GetDeployedWallets: TypedContractMethod<[], [string[]], "view">;

  deployedWallets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CreateMultiSigWallet"
  ): TypedContractMethod<[_admins: AddressLike[]], [void], "payable">;
  getFunction(
    nameOrSignature: "GetDeployedWallets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "deployedWallets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "CreateMultiSigWalletEvent"
  ): TypedContractEvent<
    CreateMultiSigWalletEventEvent.InputTuple,
    CreateMultiSigWalletEventEvent.OutputTuple,
    CreateMultiSigWalletEventEvent.OutputObject
  >;

  filters: {
    "CreateMultiSigWalletEvent(address,address,address[])": TypedContractEvent<
      CreateMultiSigWalletEventEvent.InputTuple,
      CreateMultiSigWalletEventEvent.OutputTuple,
      CreateMultiSigWalletEventEvent.OutputObject
    >;
    CreateMultiSigWalletEvent: TypedContractEvent<
      CreateMultiSigWalletEventEvent.InputTuple,
      CreateMultiSigWalletEventEvent.OutputTuple,
      CreateMultiSigWalletEventEvent.OutputObject
    >;
  };
}
