/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
import type * as iUniswapV2Router02Sol from "./IUniswapV2Router02.sol";
export type { iUniswapV2Router02Sol };
export type { IBallot } from "./IBallot";
