/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ctfSol from "./ctf.sol";
export type { ctfSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mulitsigSol from "./mulitsig.sol";
export type { mulitsigSol };
import type * as multisigFactorySol from "./multisigFactory.sol";
export type { multisigFactorySol };
import type * as multisigWuraSol from "./multisigWura.sol";
export type { multisigWuraSol };
import type * as multisigMainSol from "./multisig_main.sol";
export type { multisigMainSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { MyContract } from "./ctf.sol/MyContract";
export { MyContract__factory } from "./factories/ctf.sol/MyContract__factory";
export type { S_M } from "./ctf.sol/S_M";
export { S_M__factory } from "./factories/ctf.sol/S_M__factory";
export type { IMultiSig } from "./interfaces/IMultiSig";
export { IMultiSig__factory } from "./factories/interfaces/IMultiSig__factory";
export type { IMultiSigWura } from "./interfaces/IMultiSigWura";
export { IMultiSigWura__factory } from "./factories/interfaces/IMultiSigWura__factory";
export { Lock__factory } from "./factories/Lock__factory";
export type { Multisig } from "./mulitsig.sol/Multisig";
export { Multisig__factory } from "./factories/mulitsig.sol/Multisig__factory";
export type { MultiSigMain } from "./multisig_main.sol/MultiSigMain";
export { MultiSigMain__factory } from "./factories/multisig_main.sol/MultiSigMain__factory";
export type { MultiSigFactory } from "./multisigFactory.sol/MultiSigFactory";
export { MultiSigFactory__factory } from "./factories/multisigFactory.sol/MultiSigFactory__factory";
export type { MultiSig } from "./multisigWura.sol/MultiSig";
export { MultiSig__factory } from "./factories/multisigWura.sol/MultiSig__factory";
