/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./ballot.sol";
export type { ballotSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export * as factories from "./factories";
export type { Ballot } from "./ballot.sol/Ballot";
export { Ballot__factory } from "./factories/ballot.sol/Ballot__factory";
export type { IBallot } from "./interfaces/IBallot";
export { IBallot__factory } from "./factories/interfaces/IBallot__factory";
