/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Ballot {
  export type CategoryStruct = { name: string; voteCount: BigNumberish };

  export type CategoryStructOutput = [name: string, voteCount: bigint] & {
    name: string;
    voteCount: bigint;
  };
}

export interface BallotInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCategory"
      | "getVotingCategories"
      | "giveRightToVote"
      | "moderator"
      | "vote"
      | "voters"
      | "votingCategories"
      | "winningCategory"
      | "winningCategoryName"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "addCategory", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVotingCategories",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "giveRightToVote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "moderator", values?: undefined): string;
  encodeFunctionData(functionFragment: "vote", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "voters", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "votingCategories",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winningCategory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winningCategoryName",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "giveRightToVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moderator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winningCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winningCategoryName",
    data: BytesLike
  ): Result;
}

export interface Ballot extends BaseContract {
  connect(runner?: ContractRunner | null): Ballot;
  waitForDeployment(): Promise<this>;

  interface: BallotInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCategory: TypedContractMethod<[_name: string], [void], "nonpayable">;

  getVotingCategories: TypedContractMethod<
    [],
    [Ballot.CategoryStructOutput[]],
    "view"
  >;

  giveRightToVote: TypedContractMethod<
    [_voter: AddressLike],
    [void],
    "nonpayable"
  >;

  moderator: TypedContractMethod<[], [string], "view">;

  vote: TypedContractMethod<
    [_CategoryIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  voters: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, bigint] & {
        noOfVotes: bigint;
        hasVoted: boolean;
        vote: bigint;
      }
    ],
    "view"
  >;

  votingCategories: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { name: string; voteCount: bigint }],
    "view"
  >;

  winningCategory: TypedContractMethod<[], [bigint], "view">;

  winningCategoryName: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCategory"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getVotingCategories"
  ): TypedContractMethod<[], [Ballot.CategoryStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "giveRightToVote"
  ): TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "moderator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[_CategoryIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, boolean, bigint] & {
        noOfVotes: bigint;
        hasVoted: boolean;
        vote: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votingCategories"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { name: string; voteCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "winningCategory"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "winningCategoryName"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
