/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./ballot.sol";
export type { ballotSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
