/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMultiSig__factory } from "./IMultiSig__factory";
export { IMultiSigWura__factory } from "./IMultiSigWura__factory";
